# Generated by Django 3.2.9 on 2022-02-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project_image_1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_image_2',
        ),
    ]
